# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tuxxi/Documents/openMotor/uilib/views/forms/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 900))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("oMIconCycles.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.motorEditor = motorEditor(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorEditor.sizePolicy().hasHeightForWidth())
        self.motorEditor.setSizePolicy(sizePolicy)
        self.motorEditor.setObjectName("motorEditor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.motorEditor)
        self.verticalLayout_3.setContentsMargins(4, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.motorEditor)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBoxPropellant = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPropellant.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBoxPropellant.setObjectName("comboBoxPropellant")
        self.horizontalLayout_3.addWidget(self.comboBoxPropellant)
        self.pushButtonPropEditor = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPropEditor.sizePolicy().hasHeightForWidth())
        self.pushButtonPropEditor.setSizePolicy(sizePolicy)
        self.pushButtonPropEditor.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButtonPropEditor.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonPropEditor.setObjectName("pushButtonPropEditor")
        self.horizontalLayout_3.addWidget(self.pushButtonPropEditor)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableWidgetGrainList = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetGrainList.sizePolicy().hasHeightForWidth())
        self.tableWidgetGrainList.setSizePolicy(sizePolicy)
        self.tableWidgetGrainList.setMaximumSize(QtCore.QSize(400, 300))
        self.tableWidgetGrainList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetGrainList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidgetGrainList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetGrainList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetGrainList.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidgetGrainList.setColumnCount(2)
        self.tableWidgetGrainList.setObjectName("tableWidgetGrainList")
        self.tableWidgetGrainList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetGrainList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetGrainList.setHorizontalHeaderItem(1, item)
        self.tableWidgetGrainList.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetGrainList.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.tableWidgetGrainList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonMoveGrainUp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMoveGrainUp.setObjectName("pushButtonMoveGrainUp")
        self.horizontalLayout_2.addWidget(self.pushButtonMoveGrainUp)
        self.pushButtonMoveGrainDown = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMoveGrainDown.setObjectName("pushButtonMoveGrainDown")
        self.horizontalLayout_2.addWidget(self.pushButtonMoveGrainDown)
        self.pushButtonEditGrain = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEditGrain.setObjectName("pushButtonEditGrain")
        self.horizontalLayout_2.addWidget(self.pushButtonEditGrain)
        self.pushButtonDeleteGrain = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteGrain.setObjectName("pushButtonDeleteGrain")
        self.horizontalLayout_2.addWidget(self.pushButtonDeleteGrain)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBoxGrainGeometry = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxGrainGeometry.setObjectName("comboBoxGrainGeometry")
        self.horizontalLayout_4.addWidget(self.comboBoxGrainGeometry)
        self.pushButtonAddGrain = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddGrain.setObjectName("pushButtonAddGrain")
        self.horizontalLayout_4.addWidget(self.pushButtonAddGrain)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphWidget = graphWidget(self.centralwidget)
        self.graphWidget.setObjectName("graphWidget")
        self.verticalLayout_2.addWidget(self.graphWidget)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 150))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayoutImpulse = QtWidgets.QHBoxLayout()
        self.horizontalLayoutImpulse.setObjectName("horizontalLayoutImpulse")
        self.labelImpulseText = QtWidgets.QLabel(self.groupBox)
        self.labelImpulseText.setObjectName("labelImpulseText")
        self.horizontalLayoutImpulse.addWidget(self.labelImpulseText)
        self.labelImpulse = QtWidgets.QLabel(self.groupBox)
        self.labelImpulse.setObjectName("labelImpulse")
        self.horizontalLayoutImpulse.addWidget(self.labelImpulse)
        self.gridLayout.addLayout(self.horizontalLayoutImpulse, 1, 0, 1, 1)
        self.horizontalLayoutMotorDesignation = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMotorDesignation.setObjectName("horizontalLayoutMotorDesignation")
        self.labelMotorDesignationText = QtWidgets.QLabel(self.groupBox)
        self.labelMotorDesignationText.setObjectName("labelMotorDesignationText")
        self.horizontalLayoutMotorDesignation.addWidget(self.labelMotorDesignationText)
        self.labelMotorDesignation = QtWidgets.QLabel(self.groupBox)
        self.labelMotorDesignation.setObjectName("labelMotorDesignation")
        self.horizontalLayoutMotorDesignation.addWidget(self.labelMotorDesignation)
        self.gridLayout.addLayout(self.horizontalLayoutMotorDesignation, 0, 0, 1, 1)
        self.horizontalLayoutPeakPressure = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPeakPressure.setObjectName("horizontalLayoutPeakPressure")
        self.labelPeakPressureText = QtWidgets.QLabel(self.groupBox)
        self.labelPeakPressureText.setObjectName("labelPeakPressureText")
        self.horizontalLayoutPeakPressure.addWidget(self.labelPeakPressureText)
        self.labelPeakPressure = QtWidgets.QLabel(self.groupBox)
        self.labelPeakPressure.setObjectName("labelPeakPressure")
        self.horizontalLayoutPeakPressure.addWidget(self.labelPeakPressure)
        self.gridLayout.addLayout(self.horizontalLayoutPeakPressure, 1, 1, 1, 1)
        self.horizontalLayoutDeliveredISP = QtWidgets.QHBoxLayout()
        self.horizontalLayoutDeliveredISP.setObjectName("horizontalLayoutDeliveredISP")
        self.labelDeliveredISPText = QtWidgets.QLabel(self.groupBox)
        self.labelDeliveredISPText.setObjectName("labelDeliveredISPText")
        self.horizontalLayoutDeliveredISP.addWidget(self.labelDeliveredISPText)
        self.labelDeliveredISP = QtWidgets.QLabel(self.groupBox)
        self.labelDeliveredISP.setObjectName("labelDeliveredISP")
        self.horizontalLayoutDeliveredISP.addWidget(self.labelDeliveredISP)
        self.gridLayout.addLayout(self.horizontalLayoutDeliveredISP, 2, 0, 1, 1)
        self.horizontalLayoutPeakKN = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPeakKN.setObjectName("horizontalLayoutPeakKN")
        self.labelPeakKNText = QtWidgets.QLabel(self.groupBox)
        self.labelPeakKNText.setObjectName("labelPeakKNText")
        self.horizontalLayoutPeakKN.addWidget(self.labelPeakKNText)
        self.labelPeakKN = QtWidgets.QLabel(self.groupBox)
        self.labelPeakKN.setObjectName("labelPeakKN")
        self.horizontalLayoutPeakKN.addWidget(self.labelPeakKN)
        self.gridLayout.addLayout(self.horizontalLayoutPeakKN, 3, 1, 1, 1)
        self.horizontalLayoutBurnTime = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBurnTime.setObjectName("horizontalLayoutBurnTime")
        self.labelBurnTimeText = QtWidgets.QLabel(self.groupBox)
        self.labelBurnTimeText.setObjectName("labelBurnTimeText")
        self.horizontalLayoutBurnTime.addWidget(self.labelBurnTimeText)
        self.labelBurnTime = QtWidgets.QLabel(self.groupBox)
        self.labelBurnTime.setObjectName("labelBurnTime")
        self.horizontalLayoutBurnTime.addWidget(self.labelBurnTime)
        self.gridLayout.addLayout(self.horizontalLayoutBurnTime, 3, 0, 1, 1)
        self.horizontalLayoutInitialKN = QtWidgets.QHBoxLayout()
        self.horizontalLayoutInitialKN.setObjectName("horizontalLayoutInitialKN")
        self.labelInitialKNText = QtWidgets.QLabel(self.groupBox)
        self.labelInitialKNText.setObjectName("labelInitialKNText")
        self.horizontalLayoutInitialKN.addWidget(self.labelInitialKNText)
        self.labelInitialKN = QtWidgets.QLabel(self.groupBox)
        self.labelInitialKN.setObjectName("labelInitialKN")
        self.horizontalLayoutInitialKN.addWidget(self.labelInitialKN)
        self.gridLayout.addLayout(self.horizontalLayoutInitialKN, 2, 1, 1, 1)
        self.horizontalLayoutAveragePressure = QtWidgets.QHBoxLayout()
        self.horizontalLayoutAveragePressure.setObjectName("horizontalLayoutAveragePressure")
        self.labelAveragePressureText = QtWidgets.QLabel(self.groupBox)
        self.labelAveragePressureText.setObjectName("labelAveragePressureText")
        self.horizontalLayoutAveragePressure.addWidget(self.labelAveragePressureText)
        self.labelAveragePressure = QtWidgets.QLabel(self.groupBox)
        self.labelAveragePressure.setObjectName("labelAveragePressure")
        self.horizontalLayoutAveragePressure.addWidget(self.labelAveragePressure)
        self.gridLayout.addLayout(self.horizontalLayoutAveragePressure, 0, 1, 1, 1)
        self.horizontalLayoutPeakMassFlux = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPeakMassFlux.setObjectName("horizontalLayoutPeakMassFlux")
        self.labelPeakMassFluxText = QtWidgets.QLabel(self.groupBox)
        self.labelPeakMassFluxText.setObjectName("labelPeakMassFluxText")
        self.horizontalLayoutPeakMassFlux.addWidget(self.labelPeakMassFluxText)
        self.labelPeakMassFlux = QtWidgets.QLabel(self.groupBox)
        self.labelPeakMassFlux.setObjectName("labelPeakMassFlux")
        self.horizontalLayoutPeakMassFlux.addWidget(self.labelPeakMassFlux)
        self.gridLayout.addLayout(self.horizontalLayoutPeakMassFlux, 3, 2, 1, 1)
        self.horizontalLayoutPortThroatRatio = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPortThroatRatio.setObjectName("horizontalLayoutPortThroatRatio")
        self.labelPortThroatRatioText = QtWidgets.QLabel(self.groupBox)
        self.labelPortThroatRatioText.setObjectName("labelPortThroatRatioText")
        self.horizontalLayoutPortThroatRatio.addWidget(self.labelPortThroatRatioText)
        self.labelPortThroatRatio = QtWidgets.QLabel(self.groupBox)
        self.labelPortThroatRatio.setObjectName("labelPortThroatRatio")
        self.horizontalLayoutPortThroatRatio.addWidget(self.labelPortThroatRatio)
        self.gridLayout.addLayout(self.horizontalLayoutPortThroatRatio, 2, 2, 1, 1)
        self.horizontalLayoutPropellantLength = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPropellantLength.setObjectName("horizontalLayoutPropellantLength")
        self.labelPropellantLengthText = QtWidgets.QLabel(self.groupBox)
        self.labelPropellantLengthText.setObjectName("labelPropellantLengthText")
        self.horizontalLayoutPropellantLength.addWidget(self.labelPropellantLengthText)
        self.labelPropellantLength = QtWidgets.QLabel(self.groupBox)
        self.labelPropellantLength.setObjectName("labelPropellantLength")
        self.horizontalLayoutPropellantLength.addWidget(self.labelPropellantLength)
        self.gridLayout.addLayout(self.horizontalLayoutPropellantLength, 1, 2, 1, 1)
        self.horizontalLayoutPropellantMass = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPropellantMass.setObjectName("horizontalLayoutPropellantMass")
        self.labelPropellantMassText = QtWidgets.QLabel(self.groupBox)
        self.labelPropellantMassText.setObjectName("labelPropellantMassText")
        self.horizontalLayoutPropellantMass.addWidget(self.labelPropellantMassText)
        self.labelPropellantMass = QtWidgets.QLabel(self.groupBox)
        self.labelPropellantMass.setObjectName("labelPropellantMass")
        self.horizontalLayoutPropellantMass.addWidget(self.labelPropellantMass)
        self.gridLayout.addLayout(self.horizontalLayoutPropellantMass, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuSimulate = QtWidgets.QMenu(self.menubar)
        self.menuSimulate.setObjectName("menuSimulate")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionRunSimulation = QtWidgets.QAction(MainWindow)
        self.actionRunSimulation.setObjectName("actionRunSimulation")
        self.actionGenerateReport = QtWidgets.QAction(MainWindow)
        self.actionGenerateReport.setObjectName("actionGenerateReport")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAboutOpenMotor = QtWidgets.QAction(MainWindow)
        self.actionAboutOpenMotor.setObjectName("actionAboutOpenMotor")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setShortcutVisibleInContextMenu(False)
        self.actionNew.setObjectName("actionNew")
        self.actionENGFile = QtWidgets.QAction(MainWindow)
        self.actionENGFile.setObjectName("actionENGFile")
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setObjectName("actionImage")
        self.actionCSV = QtWidgets.QAction(MainWindow)
        self.actionCSV.setObjectName("actionCSV")
        self.actionSetKN = QtWidgets.QAction(MainWindow)
        self.actionSetKN.setObjectName("actionSetKN")
        self.actionExpansionRatio = QtWidgets.QAction(MainWindow)
        self.actionExpansionRatio.setObjectName("actionExpansionRatio")
        self.actionPropellantEditor = QtWidgets.QAction(MainWindow)
        self.actionPropellantEditor.setObjectName("actionPropellantEditor")
        self.actionMotorDiameter = QtWidgets.QAction(MainWindow)
        self.actionMotorDiameter.setObjectName("actionMotorDiameter")
        self.actionInitial_KN = QtWidgets.QAction(MainWindow)
        self.actionInitial_KN.setObjectName("actionInitial_KN")
        self.actionMax_KN = QtWidgets.QAction(MainWindow)
        self.actionMax_KN.setObjectName("actionMax_KN")
        self.actionExpansion_Ratio = QtWidgets.QAction(MainWindow)
        self.actionExpansion_Ratio.setObjectName("actionExpansion_Ratio")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionBurnsimFile = QtWidgets.QAction(MainWindow)
        self.actionBurnsimFile.setObjectName("actionBurnsimFile")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionENGFile)
        self.menuExport.addAction(self.actionImage)
        self.menuExport.addAction(self.actionCSV)
        self.menuExport.addAction(self.actionBurnsimFile)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSimulate.addSeparator()
        self.menuSimulate.addAction(self.actionRunSimulation)
        self.menuSimulate.addAction(self.actionGenerateReport)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPropellantEditor)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAboutOpenMotor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSimulate.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "openMotor"))
        self.pushButtonPropEditor.setText(_translate("MainWindow", "Propellant Editor"))
        item = self.tableWidgetGrainList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidgetGrainList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Details"))
        self.pushButtonMoveGrainUp.setText(_translate("MainWindow", "Up"))
        self.pushButtonMoveGrainDown.setText(_translate("MainWindow", "Down"))
        self.pushButtonEditGrain.setText(_translate("MainWindow", "Edit"))
        self.pushButtonDeleteGrain.setText(_translate("MainWindow", "Delete"))
        self.pushButtonAddGrain.setText(_translate("MainWindow", "Add grain"))
        self.groupBox.setTitle(_translate("MainWindow", "Motor Statistics"))
        self.labelImpulseText.setText(_translate("MainWindow", "Impulse:"))
        self.labelImpulse.setText(_translate("MainWindow", "-"))
        self.labelMotorDesignationText.setText(_translate("MainWindow", "Motor Designation:"))
        self.labelMotorDesignation.setText(_translate("MainWindow", "-"))
        self.labelPeakPressureText.setText(_translate("MainWindow", "Peak Pressure:"))
        self.labelPeakPressure.setText(_translate("MainWindow", "-"))
        self.labelDeliveredISPText.setText(_translate("MainWindow", "Delivered ISP:"))
        self.labelDeliveredISP.setText(_translate("MainWindow", "-"))
        self.labelPeakKNText.setText(_translate("MainWindow", "Peak Kn:"))
        self.labelPeakKN.setText(_translate("MainWindow", "-"))
        self.labelBurnTimeText.setText(_translate("MainWindow", "Burn Time:"))
        self.labelBurnTime.setText(_translate("MainWindow", "-"))
        self.labelInitialKNText.setText(_translate("MainWindow", "Initial Kn:"))
        self.labelInitialKN.setText(_translate("MainWindow", "-"))
        self.labelAveragePressureText.setText(_translate("MainWindow", "Average Pressure:"))
        self.labelAveragePressure.setText(_translate("MainWindow", "-"))
        self.labelPeakMassFluxText.setText(_translate("MainWindow", "Peak Mass Flux:"))
        self.labelPeakMassFlux.setText(_translate("MainWindow", "-"))
        self.labelPortThroatRatioText.setText(_translate("MainWindow", "Port/Throat Ratio:"))
        self.labelPortThroatRatio.setText(_translate("MainWindow", "-"))
        self.labelPropellantLengthText.setText(_translate("MainWindow", "Propellant Length:"))
        self.labelPropellantLength.setText(_translate("MainWindow", "-"))
        self.labelPropellantMassText.setText(_translate("MainWindow", "Propellant Mass:"))
        self.labelPropellantMass.setText(_translate("MainWindow", "-"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuSimulate.setTitle(_translate("MainWindow", "Simulate"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionRunSimulation.setText(_translate("MainWindow", "Run Simulation"))
        self.actionRunSimulation.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionGenerateReport.setText(_translate("MainWindow", "Generate Report"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionAboutOpenMotor.setText(_translate("MainWindow", "About openMotor"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionENGFile.setText(_translate("MainWindow", "ENG File"))
        self.actionImage.setText(_translate("MainWindow", "Image"))
        self.actionCSV.setText(_translate("MainWindow", "CSV"))
        self.actionSetKN.setText(_translate("MainWindow", "Set KN"))
        self.actionExpansionRatio.setText(_translate("MainWindow", "Expansion Ratio"))
        self.actionPropellantEditor.setText(_translate("MainWindow", "Propellant Editor"))
        self.actionMotorDiameter.setText(_translate("MainWindow", "Motor Diameter"))
        self.actionInitial_KN.setText(_translate("MainWindow", "Initial KN"))
        self.actionMax_KN.setText(_translate("MainWindow", "Max KN"))
        self.actionExpansion_Ratio.setText(_translate("MainWindow", "Expansion Ratio"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionBurnsimFile.setText(_translate("MainWindow", "Burnsim File"))
        self.actionImport.setText(_translate("MainWindow", "Import"))


from uilib import graphWidget, motorEditor
